### PR TITLE
Add proptypes for the PrinciplesLayout

### LINKED ISSUE #3477: [Docs] Add proptypes for children prop in the src/components/layouts/PrinciplesLayout.js file
Missing proptypes and needs eslint fixes.

### PR DESCRIPTION
**Pull request by Ahmeed2m**
## What does this PR do?
This PR adds proptypes for the `PrinciplesLayout` to fix linter warnings.

### Associated Issue
Fixes #3477

### CODE REVIEW

**Review by guern1kn — CHANGES_REQUESTED** [review]
Thanks for opening a PR!  `location` will need to be added to the propTypes and the eslint errors can be fixed. Will re-review after and get this merged!

**Comment by Ahmeed2m** [comment]
@guern1kn Added the location proptype.

**Comment by guern1kn** [comment]
@Ahmeed2m Thanks for adding that! Do you have eslint installed? There are some errors that can be fixed with that, as well.

**Comment by Ahmeed2m** [comment]
My bad :sweat_smile: I didn't have the local eslint config running. All should be fixed now.

**Review by guern1kn — APPROVED** [review]

**Comment by guern1kn** [comment]
Thank you for contributing, @Ahmeed2m !

**Pull request merged**
