### PR TITLE
adding missing packages

### PR DESCRIPTION
**Pull request by 13protons**
## What does this PR do?
Some packages were missing when cloning the repo for the first time. I added them!

### Associated Issue 
No issue associated with this (that I know of! It's my first day!)

### CODE REVIEW

**Comment by 13protons** [comment]
@RCopeland I added the missing packages w/ `npm install` and that got my test suite passing. Can you please double check the the auto populated version numbers for these packages are actually the ones we want?

**Comment by afebbraro** [comment]
Glad to see you making PRs Alan! So awesome! For the peer deps, a few are required by the eslint-lint create react app package which we decided today we no longer need. We’re using the Airbnb style guide for limiting instead. So we don’t need those peerDeps.

**Comment by yodasw16** [comment]
@13protons did you see @afebbraro's comments above? Does this just need to be closed or is there some follow-up that needs to happen?

**Comment by 13protons** [comment]
> @13protons did you see @afebbraro's comments above? Does this just need to be closed or is there some follow-up that needs to happen?

Sorry, I missed this. I opened the PR because I couldn't install and get spark running without manually installing these. I think this means that our users are in the same boat and if that's the case then these peer deps should either be called out clearly in our docs or simply included in order to reduce on-boarding friction.

**Comment by 13protons** [comment]
Also I'm not the expert here on version numbers etc, so any other necessary changes should just be made without my input

**Comment by afebbraro** [comment]
This is a pretty important issue so I made an official git issue for this, so that we can fully look into what all we need and not. https://github.com/sparkdesignsystem/spark-design-system/issues/1160. Closing this PR so the whole issue can be addressed. Thanks!

**Pull request closed without merging**
