### PR TITLE
Spacing doc update

### PR DESCRIPTION
**Pull request by afebbraro**

### CODE REVIEW

**Comment by afebbraro** [comment]
@yodasw16 Yes it does. I did that work in the last PR regarding the spacing setup. This PR is for finishing up the docs.

**Comment by afebbraro** [comment]
@RCopeland nice! Thanks! I was planning on keeping them on till Phil had a chance to give it his final approval.

**Comment by yodasw16** [comment]
I’d like to give this a good read through in the morning before finalizing,
if that’s cool.

**Comment by afebbraro** [comment]
@yodasw16 yes totally cool! No rush! I want all the feedbacks! :)

**Comment by afebbraro** [comment]
@yodasw16  thanks! Phil went through and re-read it and is okay with it.

**Pull request merged**
