### PR TITLE
Convert toggleValue Fn to an arrow fn

### PR DESCRIPTION
**Pull request by iamjoross**
## What does this PR do?
This converts the toggleValue method to an arrow function

### Associated Issue
Fixes Issue #3503 

### Code
- [x] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)

- [x] Google Chrome
- [ ] Google Chrome (Mobile)
- [ ] Mozilla Firefox
- [ ] Mozilla Firefox (Mobile)
- [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
- [ ] Microsoft Edge
- [x] Apple Safari
- [ ] Apple Safari (Mobile)

### CODE REVIEW

**Review by guern1kn — CHANGES_REQUESTED** [review]
Thanks for the PR! Let's get a semi-colon added at the end of this function and we'll get it merged!

**Comment by afebbraro** [comment]
Also please update the branch with staging. Thank you!

**Comment by iamjoross** [comment]
@guern1kn , I just pushed a commit fixing the error.

**Review by guern1kn — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
