### PR TITLE
converted to es6 arrow function

### LINKED ISSUE #3479: [DOCS] Update the function to es6 arrow function
Update the function in src/components/markdown-render/a.js to es6 arrow function

### PR DESCRIPTION
**Pull request by iadi7ya**
## What does this PR do?
Converted the existing function to ES6 arrow function

### Associated Issue
Fixes #3479 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [:white_check_mark: ] Build Component in HTML
 - [:white_check_mark: ] Build Component in Angular
 - [:white_check_mark: ] Build Component in React
 - [:white_check_mark: ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [:white_check_mark: ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [:white_check_mark: ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [:white_check_mark: ] Google Chrome
  - [:white_check_mark: ] Google Chrome (Mobile)
  - [:white_check_mark: ] Mozilla Firefox
  - [:white_check_mark: ] Mozilla Firefox (Mobile)
  - [ :white_check_mark:] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [:white_check_mark: ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

### CODE REVIEW

**Comment by iadi7ya** [comment]
Hi @afebbraro I've implemented the code for es6 arrow function, please review the PR. Thanks.

**Comment by afebbraro** [comment]
@iadi7ya  taking a look now, thank you!

**Comment by afebbraro** [comment]
@iadi7ya looks great! Will merge tomorrow so that you get hacktoberfest credit since it starts October 1.

**Comment by iadi7ya** [comment]
> @iadi7ya looks great! Will merge tomorrow so that you get hacktoberfest credit since it starts October 1.

Thanks!

**Pull request merged**
