### PR TITLE
add flexbox utils for general purpose use

### PR DESCRIPTION
**Pull request by clinta74**
## What does this PR do?
Adds flexbox utils for layouts or styling of elements used inside other controls.

### Associated Issue
N/A New Item

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [X ] Update Spark Docs

### Browser Testing (current version and 1 prior)
  - [X] Google Chrome
  - [X] Google Chrome (Mobile)
  - [X] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [X] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

### CODE REVIEW

**Comment by afebbraro** [comment]
hey @clinta74 , could you setup a meeting with us regarding this for the end of next week?

**Comment by afebbraro** [comment]
@RCopeland, I think you have been in contact with @clinta74. I commented on here last week about setting up a meeting with us. Do you think you could reach out to them to do so? I'm not sure if they check github messages.

**Comment by clinta74** [comment]
> @RCopeland, I think you have been in contact with @clinta74. I commented on here last week about setting up a meeting with us. Do you think you could reach out to them to do so? I'm not sure if they check github messages.

Sorry I don't look at it a lot. I am happy to setup a meeting.

**Comment by RCopeland** [comment]
## Meeting Notes
- want to enhance stack rather than add utility classes
- would like to enhance stack's css to cover the following use cases:
  - flex-grow
  - inline-flex
  - align-items baseline
  - justify-content: space-between, space-around, space-evenly
- possible new stories to show options

Closing PR and opening a new issue

**Pull request closed without merging**
