### PR TITLE
Updated isValidDate to be an arrow function

### PR DESCRIPTION
**Pull request by adrikagupta**
## What does this PR do?
Changes the traditional isValidDate function to an arrow function

### Associated Issue
Fixes (#3504)

### CODE REVIEW

**Review by guern1kn — CHANGES_REQUESTED** [review]
Thanks for the PR! There are some eslint errors that can be cleaned up here, then we'll get it merged!

**Comment by guern1kn** [comment]
@adrikagupta Thanks for the PR! This issue is currently assigned to someone else. You'll still get credit for Hacktoberfest for opening the PR, but we're going to give the person assigned a chance to complete the task. If they don't, then we'll get yours merged. Thanks again!

**Comment by adrikagupta** [comment]
> @adrikagupta Thanks for the PR! This issue is currently assigned to someone else. You'll still get credit for Hacktoberfest for opening the PR, but we're going to give the person assigned a chance to complete the task. If they don't, then we'll get yours merged. Thanks again!

I am working on the changes you have requested. Yeah no problem, I understand. Is there a way I can be assigned this task too? Just asking 'cause I am new and I don't know if we can have multiple assignees. Thanks:)

**Comment by guern1kn** [comment]
@adrikagupta Hi there! This task was completed by the original person assigned. In this particular case, only one person could be assigned. Please browse through our  unassigned issues and see if anything peaks your interest. I'll be happy to help or answer any questions you may have!

**Pull request closed without merging**
