### PR TITLE
update icon color for simple links in masthead on hover

### LINKED ISSUE #3576: Bug: Icon Masthead will be black on hover
image
**User Story:**
As Spark, I want Dropdown Links in React Masthead to be styled back.

**Notes:** 
Requestor: Sme, Bob

**Current State:**
Dropdown links in React Masthead are styled purple, should be black

**AC:**
- Dropdown Links in Masthead will be black.
- React will match HTML and Angular

### PR DESCRIPTION
**Pull request by guern1kn**
## What does this PR do?
Updates the icon color for links in Masthead that are 'simple' links and have an icon.

### Associated Issue
Fixes #3576 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Code
 - [x] Build Component in HTML
 - [x] Build Component in Angular
 - [x] Build Component in React
 - [x] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [x] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [x] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [x] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [x] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### CODE REVIEW

**Comment by afebbraro** [comment]
@guern1kn  its late and I might be looking at this wrong but the issue shows different colors than the deploy preview. I see black links on hover. But the issue shows purple? 
Screen Shot 2020-10-27 at 3 46 00 PM

**Comment by guern1kn** [comment]
@afebbraro Yeah, the issue screenshot showed the problem. That the icons were purple on hover. The style should be black text, black icon and red underline.

**Review by afebbraro — APPROVED** [review]

**Review by afebbraro — CHANGES_REQUESTED** [review]
hold up on merging this for a min

**Review by afebbraro — APPROVED** [review]
branch is fixed and this is good to go

**Pull request merged**
